### ISSUE TITLE
Hierarchical Voronoi Tessellation plots | L1 L2 L3 lines overlapping

### ISSUE THREAD

**Issue by SangeetM** [Mu-Sigma/muHVT#10]

**Comment by shubhra2503** [comment]
Overlapping lines for L1 L2 and L3. 
![lines overlap](https://user-images.githubusercontent.com/53158022/72152597-7c036480-33d1-11ea-8976-0c16f59571bf.png)

**Comment by shubhra2503** [comment]
Layer wise rendering of plots for different depths fixed the issue

**Comment by shubhra2503** [comment]
![Fixed L1 L2 and L3](https://user-images.githubusercontent.com/53158022/72152853-3b581b00-33d2-11ea-9284-14b6361447f1.png)
