### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [Mu-Sigma/muHVT#54]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023.

muHVT imports 'rgeos' using `rgeos::intersect` found by `pkgapi`, not in NAMESPACE, lines 23, 36 in R/Corrected_Tessellations.R. The use of `rgeos::intersect` was a work-around the licence problems in `gpclib`, so I'm unsure whether the `geos` package is a good match, but is probably closest. If you need to copy code from `rgeos` as a wrapper to `geos`, please do so, but you also use `sp::point.in.polygon` (not retiring but not actively maintained), so you may want to review your approach. Anyway, please fix the `rgeos` dependency best by June, latest October 2023 to avoid CRAN checks failing.

**Comment by rsbivand** [comment]
@Somya.Shambhawi @musigma-admin See also https://r-spatial.org/r/2023/05/15/evolution4.html. I see positive changes appearing in the repository, please ask if help is needed to remove retiring packages. Less than three months remain.

**Comment by Somya545** [comment]
Hi Roger, 
Thanks for your attention to the repository! We've have gone through your 4th evolution report and  removed all the retiring packages. If you have any other suggestions or need further assistance, please drop a note here.

**Comment by rsbivand** [comment]
@Somya545 Good to hear. Please tidy up the remaining (non-r-spatial problems) and release after August 7 but before October.

**Comment by rsbivand** [comment]
@Somya545 Please submit to CRAN as soon as possible, less than three weeks remain

**Comment by rsbivand** [comment]
@Somya545 R spatial infrastructure packages maptools, rgdal and rgeos will be archived by CRAN on Monday, October 16, 2023. Your package does not pass CMD check when these packages are not available. Expect your package to be archived by CRAN October 17-18 as CRAN checks feed through and your package fails, if not updated by Monday, October 16, 2023. 

No grace period is anticipated, as you have had sufficient time to update your package to remove dependencies on maptools, rgdal and/or rgeos.

**Comment by chepuri-krishna** [comment]
This repository has been archived. All future updates and releases will be made available in [Mu-Sigma/HVT](https://github.com/Mu-Sigma/HVT) repository. Similarly, CRAN package [muHVT](https://cran.r-project.org/web/packages/muHVT/) has been discontinued and all the future releases will be made available on [HVT](https://cran.r-project.org/web/packages/HVT/) package.
