### ISSUE TITLE
Make gifski suggested package, but not required

### ISSUE THREAD

**Issue by barracuda156** [Mu-Sigma/muHVT#74]
Is it possible to avoid a hard dependency of `gifski`? That package pulls in a dependency on rust, which is unjustifiably huge to build and broken on some non-mainstream platforms (OpenBSD and macOS on ppc, for example).

**Comment by chepuri-krishna** [comment]
This repository has been archived. All future updates and releases will be made available in [Mu-Sigma/HVT](https://github.com/Mu-Sigma/HVT) repository. Similarly, CRAN package [muHVT](https://cran.r-project.org/web/packages/muHVT/) has been discontinued and all the future releases will be made available on [HVT](https://cran.r-project.org/web/packages/HVT/) package.
